[package]
edition = "2021"
name = "greeting"
version = "0.1.0"

[dependencies]
alloy-sol-types = {version = "0.7.4", default-features = false}

fluentbase-sdk = {git = "https://github.com/fluentlabs-xyz/fluentbase", default-features = false}
rand = { version = "0.8.3", features = ["small_rng"], default-features = false }
[lib]
crate-type = ["cdylib", "staticlib"]
path = "lib.rs"

[profile.release]
lto = true
opt-level = 'z'
panic = "abort"
strip = true

[features]
default = []
std = [
  "fluentbase-sdk/std",
]
